version: "3"

services:
  nginx:
    image: nginx:1.14.0
    volumes:
      - ./webapp/nginx/conf:/etc/nginx
      - ./webapp/frontend:/www
    ports:
      - 127.0.0.1:8000:80
    networks:
      - frontend
  webapp:
    build: ./webapp/python
    volumes:
      - ./webapp/mysql:/app/webapp/mysql
      - ./webapp/fixture:/app/webapp/fixture
      - ./webapp/python:/app/webapp/python
    expose:
      - 1323
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=isucon
      - MYSQL_PASS=isucon
    networks:
      - frontend
      - backend
  db:
    build: ./webapp/mysql
    volumes:
      - ./webapp/mysql/db:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_HOST=localhost
      - MYSQL_USER=isucon
      - MYSQL_PASSWORD=isucon
      - MYSQL_DATABASE=isuumo
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
