version: "3"

services:
  nginx:
    image: nginx:1.14.0
    volumes:
      - ./webapp/nginx/conf:/etc/nginx
      - ./webapp/frontend:/www
    ports:
      - 127.0.0.1:8000:80
    networks:
      - frontend
  webapp:
    build: ./webapp/python
    volumes:
      - .:/app
    expose:
      - 1323
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=isucon
      - MYSQL_PASS=isucon
    networks:
      - frontend
      - backend
  db:
    image: mysql:5.7
    volumes:
      - ./webapp/mysql:/docker-entrypoint-initdb.d
      - ./webapp/mysql/conf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_HOST=127.0.0.01
      - MYSQL_USER=isucon
      - MYSQL_PASSWORD=isucon
      - MYSQL_DATABASE=isuumo
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
